# Generated by Django 3.2.2 on 2021-05-25 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='prescription',
            field=models.TextField(default='hello'),
            preserve_default=False,
        ),
    ]
