# Generated by Django 3.2.2 on 2021-05-26 03:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(regex='/^(\\+\\d{1,3}[- ]?)?\\d{10}$/')]),
        ),
    ]
