# Generated by Django 3.2.2 on 2021-05-29 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_alter_userprofile_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='attendance',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='case_paper',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='med_rps',
        ),
    ]
